export interface CompanyRow {
  id: string;
  userId: string;
  companyName: string;
  industry: string;
  location: string;
  websiteUrl: string;
  companySize: string;
  companyType: string;
  subscription: string;
  status: string;
  jobsPosted: number;
  memberSince: string;
  image: string | null;
  email: string;
}

export const dummyCompanies: CompanyRow[] = [
  {
    id: "dummy-1",
    userId: "user-dummy-1",
    companyName: "Acme Corporation",
    industry: "Technology",
    location: "San Francisco, CA",
    websiteUrl: "https://acme.com",
    companySize: "Enterprise (1000+ employees)",
    companyType: "Public",
    subscription: "Enterprise",
    status: "Active",
    jobsPosted: 12,
    memberSince: "2025-01-15T08:30:00.000Z",
    image: null,
    email: "info@acme.com",
  },
  {
    id: "dummy-2",
    userId: "user-dummy-2",
    companyName: "Stark Industries",
    industry: "Defense & Aerospace",
    location: "Los Angeles, CA",
    websiteUrl: "https://starkindustries.com",
    companySize: "Enterprise (5000+ employees)",
    companyType: "Private",
    subscription: "Pro+",
    status: "Active",
    jobsPosted: 8,
    memberSince: "2025-02-20T10:15:00.000Z",
    image: null,
    email: "contact@stark.com",
  },
  {
    id: "dummy-3",
    userId: "user-dummy-3",
    companyName: "Wayne Enterprises",
    industry: "Conglomerate",
    location: "Gotham City",
    websiteUrl: "https://waynecorp.com",
    companySize: "Enterprise (10000+ employees)",
    companyType: "Public",
    subscription: "Pro",
    status: "Inactive",
    jobsPosted: 0,
    memberSince: "2025-03-05T14:45:00.000Z",
    image: null,
    email: "hr@waynecorp.com",
  },
  {
    id: "dummy-4",
    userId: "user-dummy-4",
    companyName: "Cyberdyne Systems",
    industry: "Robotics & AI",
    location: "Sunnyvale, CA",
    websiteUrl: "https://cyberdyne.co",
    companySize: "Mid-size (100-500 employees)",
    companyType: "Private",
    subscription: "Free",
    status: "Banned",
    jobsPosted: 0,
    memberSince: "2025-04-12T11:00:00.000Z",
    image: null,
    email: "sysadmin@cyberdyne.co",
  },
  {
    id: "dummy-5",
    userId: "user-dummy-5",
    companyName: "Oscorp Technologies",
    industry: "Biotechnology",
    location: "New York, NY",
    websiteUrl: "https://oscorp.com",
    companySize: "Enterprise (2000+ employees)",
    companyType: "Private",
    subscription: "Enterprise",
    status: "Active",
    jobsPosted: 15,
    memberSince: "2025-05-18T16:20:00.000Z",
    image: null,
    email: "careers@oscorp.com",
  },
  {
    id: "dummy-6",
    userId: "user-dummy-6",
    companyName: "Tyrell Corporation",
    industry: "Artificial Intelligence",
    location: "Los Angeles, CA",
    websiteUrl: "https://tyrell.co",
    companySize: "Enterprise (1000+ employees)",
    companyType: "Private",
    subscription: "Pro+",
    status: "Active",
    jobsPosted: 5,
    memberSince: "2025-06-01T09:00:00.000Z",
    image: null,
    email: "replicants@tyrell.co",
  },
  {
    id: "dummy-7",
    userId: "user-dummy-7",
    companyName: "Weyland-Yutani Corp",
    industry: "Space Technology",
    location: "Houston, TX",
    websiteUrl: "https://weyland-yutani.com",
    companySize: "Enterprise (50000+ employees)",
    companyType: "Public",
    subscription: "Enterprise",
    status: "Active",
    jobsPosted: 22,
    memberSince: "2025-06-10T14:30:00.000Z",
    image: null,
    email: "inquiries@weyland.com",
  },
  {
    id: "dummy-8",
    userId: "user-dummy-8",
    companyName: "Umbrella Corporation",
    industry: "Pharmaceuticals",
    location: "Raccoon City",
    websiteUrl: "https://umbrella.co",
    companySize: "Enterprise (5000+ employees)",
    companyType: "Public",
    subscription: "Pro",
    status: "Banned",
    jobsPosted: 0,
    memberSince: "2025-06-25T11:15:00.000Z",
    image: null,
    email: "security@umbrella.co",
  },
  {
    id: "dummy-9",
    userId: "user-dummy-9",
    companyName: "Aperture Science",
    industry: "Research & Development",
    location: "Cleveland, OH",
    websiteUrl: "https://aperturescience.com",
    companySize: "Mid-size (50-200 employees)",
    companyType: "Private",
    subscription: "Free",
    status: "Inactive",
    jobsPosted: 1,
    memberSince: "2025-07-02T10:00:00.000Z",
    image: null,
    email: "glados@aperture.com",
  },
  {
    id: "dummy-10",
    userId: "user-dummy-10",
    companyName: "Black Mesa Research",
    industry: "Defense & Scientific Research",
    location: "New Mexico",
    websiteUrl: "https://blackmesa.gov",
    companySize: "Enterprise (1500+ employees)",
    companyType: "Government",
    subscription: "Pro+",
    status: "Active",
    jobsPosted: 9,
    memberSince: "2025-07-15T08:00:00.000Z",
    image: null,
    email: "freeman@blackmesa.gov",
  },
  {
    id: "dummy-11",
    userId: "user-dummy-11",
    companyName: "InGen Bioengineering",
    industry: "Genetic Engineering",
    location: "San Diego, CA",
    websiteUrl: "https://ingen.com",
    companySize: "Mid-size (200-500 employees)",
    companyType: "Private",
    subscription: "Pro",
    status: "Inactive",
    jobsPosted: 2,
    memberSince: "2025-08-01T15:20:00.000Z",
    image: null,
    email: "hammond@ingen.com",
  },
  {
    id: "dummy-12",
    userId: "user-dummy-12",
    companyName: "Hooli",
    industry: "Technology & Search",
    location: "Mountain View, CA",
    websiteUrl: "https://hooli.xyz",
    companySize: "Enterprise (8000+ employees)",
    companyType: "Public",
    subscription: "Enterprise",
    status: "Active",
    jobsPosted: 34,
    memberSince: "2025-08-14T09:45:00.000Z",
    image: null,
    email: "gavin.belson@hooli.xyz",
  },
  {
    id: "dummy-13",
    userId: "user-dummy-13",
    companyName: "Pied Piper",
    industry: "Data Compression",
    location: "Palo Alto, CA",
    websiteUrl: "https://piedpiper.com",
    companySize: "Startup (1-50 employees)",
    companyType: "Private",
    subscription: "Free",
    status: "Active",
    jobsPosted: 4,
    memberSince: "2025-08-20T11:30:00.000Z",
    image: null,
    email: "richard@piedpiper.com",
  },
  {
    id: "dummy-14",
    userId: "user-dummy-14",
    companyName: "Massive Dynamic",
    industry: "Science & Conglomerate",
    location: "New York, NY",
    websiteUrl: "https://massivedynamic.com",
    companySize: "Enterprise (10000+ employees)",
    companyType: "Public",
    subscription: "Enterprise",
    status: "Active",
    jobsPosted: 11,
    memberSince: "2025-09-01T14:10:00.000Z",
    image: null,
    email: "bell@massivedynamic.com",
  },
  {
    id: "dummy-15",
    userId: "user-dummy-15",
    companyName: "Gekko & Co",
    industry: "Finance & Investment",
    location: "New York, NY",
    websiteUrl: "https://gekkoco.com",
    companySize: "Mid-size (100-300 employees)",
    companyType: "Private",
    subscription: "Pro+",
    status: "Inactive",
    jobsPosted: 0,
    memberSince: "2025-09-12T16:00:00.000Z",
    image: null,
    email: "gordon.gekko@gekkoco.com",
  },
  {
    id: "dummy-16",
    userId: "user-dummy-16",
    companyName: "Sterling Cooper",
    industry: "Marketing & Advertising",
    location: "New York, NY",
    websiteUrl: "https://sterlingcooper.com",
    companySize: "Startup (50-100 employees)",
    companyType: "Private",
    subscription: "Pro",
    status: "Active",
    jobsPosted: 3,
    memberSince: "2025-09-22T10:30:00.000Z",
    image: null,
    email: "draper@sterlingcooper.com",
  },
  {
    id: "dummy-17",
    userId: "user-dummy-17",
    companyName: "Dunder Mifflin Paper",
    industry: "Paper Distribution",
    location: "Scranton, PA",
    websiteUrl: "https://dundermifflin.com",
    companySize: "Mid-size (200-400 employees)",
    companyType: "Public",
    subscription: "Free",
    status: "Active",
    jobsPosted: 1,
    memberSince: "2025-10-05T09:00:00.000Z",
    image: null,
    email: "m.scott@dundermifflin.com",
  },
  {
    id: "dummy-18",
    userId: "user-dummy-18",
    companyName: "Vandelay Industries",
    industry: "Import & Export",
    location: "New York, NY",
    websiteUrl: "https://vandelay.com",
    companySize: "Startup (1-10 employees)",
    companyType: "Private",
    subscription: "Free",
    status: "Inactive",
    jobsPosted: 0,
    memberSince: "2025-10-18T14:50:00.000Z",
    image: null,
    email: "costanza@vandelay.com",
  },
  {
    id: "dummy-19",
    userId: "user-dummy-19",
    companyName: "Oceanic Airlines",
    industry: "Aviation",
    location: "Sydney, Australia",
    websiteUrl: "https://flyoceanic.com",
    companySize: "Enterprise (2000+ employees)",
    companyType: "Public",
    subscription: "Pro+",
    status: "Banned",
    jobsPosted: 0,
    memberSince: "2025-11-01T12:00:00.000Z",
    image: null,
    email: "flight815@flyoceanic.com",
  },
  {
    id: "dummy-20",
    userId: "user-dummy-20",
    companyName: "Wonka Industries",
    industry: "Confectionery",
    location: "London, UK",
    websiteUrl: "https://wonkachocolates.com",
    companySize: "Mid-size (300-600 employees)",
    companyType: "Private",
    subscription: "Enterprise",
    status: "Active",
    jobsPosted: 6,
    memberSince: "2025-11-15T15:15:00.000Z",
    image: null,
    email: "willy@wonka.com",
  }
];
