export interface CandidateRow {
  id: string;
  userId: string;
  name: string;
  email: string;
  image: string | null;
  jobTitle: string;
  experience: string;
  status: string;
  applicationsCount: number;
  memberSince: string;
  subscription?: string;
}

export const dummyCandidates: CandidateRow[] = [
  {
    id: "cand-dummy-1",
    userId: "user-cand-1",
    name: "Luke Skywalker",
    email: "luke@alliance.org",
    image: null,
    jobTitle: "AI & Machine Learning Architect",
    experience: "Lead",
    status: "Active",
    applicationsCount: 8,
    memberSince: "2025-01-10T09:00:00.000Z",
  },
  {
    id: "cand-dummy-2",
    userId: "user-cand-2",
    name: "Leia Organa",
    email: "leia@senate.gov",
    image: null,
    jobTitle: "Technical Product Manager",
    experience: "Senior",
    status: "Active",
    applicationsCount: 12,
    memberSince: "2025-01-20T10:15:00.000Z",
  },
  {
    id: "cand-dummy-3",
    userId: "user-cand-3",
    name: "Han Solo",
    email: "han@millenniumfalcon.net",
    image: null,
    jobTitle: "Database Administrator",
    experience: "Mid-level",
    status: "Active",
    applicationsCount: 4,
    memberSince: "2025-02-05T14:30:00.000Z",
  },
  {
    id: "cand-dummy-4",
    userId: "user-cand-4",
    name: "Anakin Skywalker",
    email: "vader@empire.com",
    image: null,
    jobTitle: "Senior DevOps Engineer",
    experience: "Senior",
    status: "Banned",
    applicationsCount: 0,
    memberSince: "2025-02-18T11:00:00.000Z",
  },
  {
    id: "cand-dummy-5",
    userId: "user-cand-5",
    name: "Obi-Wan Kenobi",
    email: "ben@tatooine.net",
    image: null,
    jobTitle: "Cybersecurity Analyst",
    experience: "Lead",
    status: "Inactive",
    applicationsCount: 2,
    memberSince: "2025-03-01T08:00:00.000Z",
  },
  {
    id: "cand-dummy-6",
    userId: "user-cand-6",
    name: "Frodo Baggins",
    email: "frodo@shire.me",
    image: null,
    jobTitle: "Junior Frontend Developer",
    experience: "Junior",
    status: "Active",
    applicationsCount: 5,
    memberSince: "2025-03-12T16:20:00.000Z",
  },
  {
    id: "cand-dummy-7",
    userId: "user-cand-7",
    name: "Samwise Gamgee",
    email: "sam@shire.me",
    image: null,
    jobTitle: "UI/UX Designer",
    experience: "Junior",
    status: "Active",
    applicationsCount: 6,
    memberSince: "2025-03-15T09:45:00.000Z",
  },
  {
    id: "cand-dummy-8",
    userId: "user-cand-8",
    name: "Aragorn Elessar",
    email: "strider@gondor.org",
    image: null,
    jobTitle: "Engineering Director",
    experience: "Lead",
    status: "Active",
    applicationsCount: 3,
    memberSince: "2025-03-25T13:10:00.000Z",
  },
  {
    id: "cand-dummy-9",
    userId: "user-cand-9",
    name: "Gandalf Grey",
    email: "gandalf@istari.com",
    image: null,
    jobTitle: "Cloud Solutions Architect",
    experience: "Lead",
    status: "Active",
    applicationsCount: 15,
    memberSince: "2025-04-02T10:00:00.000Z",
  },
  {
    id: "cand-dummy-10",
    userId: "user-cand-10",
    name: "Harry Potter",
    email: "harry@hogwarts.edu",
    image: null,
    jobTitle: "Mobile App Developer",
    experience: "Mid-level",
    status: "Active",
    applicationsCount: 7,
    memberSince: "2025-04-15T09:00:00.000Z",
  },
  {
    id: "cand-dummy-11",
    userId: "user-cand-11",
    name: "Hermione Granger",
    email: "hermione@hogwarts.edu",
    image: null,
    jobTitle: "Data Scientist & Analytics Lead",
    experience: "Senior",
    status: "Active",
    applicationsCount: 20,
    memberSince: "2025-04-16T10:30:00.000Z",
  },
  {
    id: "cand-dummy-12",
    userId: "user-cand-12",
    name: "Ron Weasley",
    email: "ron@hogwarts.edu",
    image: null,
    jobTitle: "QA Testing Specialist",
    experience: "Junior",
    status: "Inactive",
    applicationsCount: 1,
    memberSince: "2025-04-20T14:20:00.000Z",
  },
  {
    id: "cand-dummy-13",
    userId: "user-cand-13",
    name: "Bruce Wayne",
    email: "bruce@waynecorp.com",
    image: null,
    jobTitle: "Systems Security Engineer",
    experience: "Senior",
    status: "Active",
    applicationsCount: 4,
    memberSince: "2025-05-01T22:00:00.000Z",
  },
  {
    id: "cand-dummy-14",
    userId: "user-cand-14",
    name: "Clark Kent",
    email: "ckent@dailyplanet.com",
    image: null,
    jobTitle: "Technical Writer & Copywriter",
    experience: "Mid-level",
    status: "Active",
    applicationsCount: 9,
    memberSince: "2025-05-12T08:30:00.000Z",
  },
  {
    id: "cand-dummy-15",
    userId: "user-cand-15",
    name: "Peter Parker",
    email: "pparker@dailybugle.com",
    image: null,
    jobTitle: "React Native Developer",
    experience: "Junior",
    status: "Active",
    applicationsCount: 11,
    memberSince: "2025-05-18T16:15:00.000Z",
  },
  {
    id: "cand-dummy-16",
    userId: "user-cand-16",
    name: "Tony Stark",
    email: "tony@stark.com",
    image: null,
    jobTitle: "Embedded Systems Specialist",
    experience: "Lead",
    status: "Active",
    applicationsCount: 14,
    memberSince: "2025-05-25T11:00:00.000Z",
  },
  {
    id: "cand-dummy-17",
    userId: "user-cand-17",
    name: "Steve Rogers",
    email: "cap@avengers.org",
    image: null,
    jobTitle: "Agile Scrum Master",
    experience: "Senior",
    status: "Active",
    applicationsCount: 3,
    memberSince: "2025-06-01T09:00:00.000Z",
  },
  {
    id: "cand-dummy-18",
    userId: "user-cand-18",
    name: "Natasha Romanoff",
    email: "blackwidow@shield.gov",
    image: null,
    jobTitle: "Penetration Tester",
    experience: "Senior",
    status: "Active",
    applicationsCount: 5,
    memberSince: "2025-06-05T12:00:00.000Z",
  },
  {
    id: "cand-dummy-19",
    userId: "user-cand-19",
    name: "Bruce Banner",
    email: "hulk@avengers.org",
    image: null,
    jobTitle: "Bioinformatics Research Lead",
    experience: "Lead",
    status: "Inactive",
    applicationsCount: 2,
    memberSince: "2025-06-12T15:40:00.000Z",
  },
  {
    id: "cand-dummy-20",
    userId: "user-cand-20",
    name: "Thor Odinson",
    email: "thor@asgard.net",
    image: null,
    jobTitle: "Database Site Reliability Engineer",
    experience: "Mid-level",
    status: "Banned",
    applicationsCount: 0,
    memberSince: "2025-06-20T17:15:00.000Z",
  }
];
